language: csharp
solution: fadm.sln
install:
  - nuget restore fadm.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release-ci fadm.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Fadm.UnitTests/bin/Release-ci/Fadm.UnitTests.dll